version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:18.2.0

commands:
  list_files:
    steps:
      - run:
          name: Listing files
          command: |
            find "/home/circleci" -maxdepth 3

  store_node_modules_cache:
    steps:
      - save_cache:
          key: node-modules-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  restore_node_modules_cache:
    steps:
      - restore_cache:
          keys:
            - node-modules-v1-{{ checksum "package-lock.json" }}
            - node-modules-v1-

jobs:
  add_file:
    executor: node
    parameters:
      filename:
        type: string
        default: list
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - list_files
      - run:
          name: Create file << parameters.filename >>
          command: |
            find "$PWD" -maxdepth 3 > << parameters.filename >>
            find "$PWD" -maxdepth 3 > ../cached_<< parameters.filename >>
      - list_files
      - persist_to_workspace:
          root: ~/
          paths:
            - ./project/<< parameters.filename >>
            - ./cached_<< parameters.filename >>

  check_workspace_structure:
    executor: node
    parameters:
      attach_at:
        type: string
        default: ./
    steps:
      - attach_workspace:
          at: << parameters.attach_at >>
      - list_files

  npm_install_no_cache:
    executor: node
    parameters:
      attach_at:
        type: string
        default: ./
      command:
        type: string
        default: i
    steps:
      - checkout
      - attach_workspace:
          at: << parameters.attach_at >>
      - run:
          command: |
            npm << parameters.command >>
      - list_files

workflows:
  test_pipelines:
    jobs:
      - add_file:
          name: Create List A
          filename: list_A
      - add_file:
          name: Create List B
          filename: list_B
          filters:
            tags:
              only: /^b-*/
      - add_file:
          name: Create List A -> C
          filename: list_AC
          requires:
            - "Create List A"
      - add_file:
          name: Create List B -> D
          filename: list_BD
          requires:
            - "Create List B"
      - add_file:
          name: Create List A -> C + B -> D
          filename: list_AC_BD
          requires:
            - "Create List A -> C"
            - "Create List B -> D"
      - check_workspace_structure:
          name: Check List A at ~/
          attach_at: ~/
          requires:
            - "Create List A"
      - check_workspace_structure:
          name: Check List A at ./
          attach_at: ./
          requires:
            - "Create List A"
      - check_workspace_structure:
          name: Check List E at ~/
          attach_at: ~/
          requires:
            - "Create List A -> C + B -> D"
      - check_workspace_structure:
          name: Check List E at ./
          attach_at: ./
          requires:
            - "Create List A -> C + B -> D"

      - npm_install_no_cache:
          name: 01 NPM no cache install
      - npm_install_no_cache:
          name: 02 NPM no cache install
          requires:
            - 01 NPM no cache install

      - npm_install_no_cache:
          name: 01 NPM no cache CI install
          command: ci
      - npm_install_no_cache:
          name: 02 NPM no cache CI install
          command: ci
          requires:
            - 01 NPM no cache CI install
