version: 2.1

parameters:
  action:
    type: enum
    enum: [database, folders]
    default: folders

executors:
  node:
    docker:
      - image: cimg/node:18.2.0

commands:
  version_echo:
    steps:
      - run:
          name: Version
          command: |
            echo "${CIRCLE_BRANCH}:${CIRCLE_SHA1}:${CIRCLE_TAG}"

  list_files:
    steps:
      - run:
          name: Listing files
          command: |
            find "/home/circleci" -maxdepth 5

  store_node_modules_cache:
    steps:
      - save_cache:
          key: node-modules-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  restore_node_modules_cache:
    steps:
      - restore_cache:
          keys:
            - node-modules-v1-{{ checksum "package-lock.json" }}
            - node-modules-v1-

jobs:
  add_file:
    executor: node
    parameters:
      filename:
        type: string
        default: list
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - list_files
      - run:
          name: Create file << parameters.filename >>
          command: |
            find "$PWD" -maxdepth 3 > << parameters.filename >>
            find "$PWD" -maxdepth 3 > ../cached_<< parameters.filename >>
      - list_files
      - persist_to_workspace:
          root: ~/
          paths:
            - ./project/<< parameters.filename >>
            - ./cached_<< parameters.filename >>

  check_workspace_structure:
    executor: node
    parameters:
      attach_at:
        type: string
        default: ./
    steps:
      - attach_workspace:
          at: << parameters.attach_at >>
      - version_echo
      - list_files

  npm_install_no_cache:
    executor: node
    parameters:
      attach_at:
        type: string
        default: ./
      command:
        type: string
        default: i
    steps:
      - checkout
      - attach_workspace:
          at: << parameters.attach_at >>
      - run:
          command: |
            npm << parameters.command >>
      - list_files

  npm_install_cached_in_workspace:
    executor: node
    parameters:
      command:
        type: string
        default: i
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          command: |
            npm << parameters.command >>
      - list_files
      - persist_to_workspace:
          root: ~/
          paths:
            - ".npm"
            - "project/node_modules"

  npm_install_cached_in_cache:
    executor: node
    parameters:
      command:
        type: string
        default: i
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-package-v1-{{ checksum "package-lock.json" }}
      - run:
          command: |
            [ ! -d node_modules ] && npm << parameters.command >> || echo 'Using cache...'
      - list_files
      - save_cache:
          key: node-package-v1-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

  docker_compose_build:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Build application
          command: |
            export TAG="${CIRCLE_BRANCH/\//_}_${CIRCLE_TAG:-latest}"
            docker-compose -f ./docker-compose.yml build

  docker_compose_up:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Start application
          command: |
            export TAG="${CIRCLE_BRANCH/\//_}_${CIRCLE_TAG:-latest}"
            docker-compose -f ./docker-compose.yml up -d
      - run:
          name: Wait for application
          command: sleep 10
      - run:
          name: Request database state
          command: |
            docker exec circle-ci-postgres-db psql -U postgres postgres -c \dt+
            docker exec circle-ci-postgres-db psql -U postgres postgres -c "SELECT * FROM test;"

workflows:
  test_database:
    when:
      equal: [ database, << pipeline.parameters.action >> ]
    jobs:
      - docker_compose_build
      - docker_up_approve:
          type: approval
          requires:
            - docker_compose_build
      - docker_compose_up:
          requires:
            - docker_up_approve


  test_pipelines:
    when:
      equal: [ folders, << pipeline.parameters.action >> ]
    jobs:
      - add_file:
          name: Create List A
          filename: list_A
          filters:
            tags:
              only: /^a-.*/
      - add_file:
          name: Create List B
          filename: list_B
          filters:
            tags:
              only: /^b-.*/
      - add_file:
          name: Create List A -> C
          filename: list_AC
          requires:
            - "Create List A"
          filters:
            tags:
              only: /^a-.*/
      - add_file:
          name: Create List B -> D
          filename: list_BD
          requires:
            - "Create List B"
          filters:
            tags:
              only: /^b-.*/
      - add_file:
          name: Create List A -> C + B -> D
          filename: list_AC_BD
          requires:
            - "Create List A -> C"
            - "Create List B -> D"
          filters:
            tags:
              only: /^(a|b)-.*/
      - check_workspace_structure:
          name: Check List A at ~/
          attach_at: ~/
          requires:
            - "Create List A"
          filters:
            tags:
              only: /^a-.*/
      - check_workspace_structure:
          name: Check List A at ./
          attach_at: ./
          requires:
            - "Create List A"
          filters:
            tags:
              only: /^a-.*/
      - check_workspace_structure:
          name: Check List E at ~/
          attach_at: ~/
          requires:
            - "Create List A -> C + B -> D"
          filters:
            tags:
              only: /^(a|b)-.*/
      - check_workspace_structure:
          name: Check List E at ./
          attach_at: ./
          requires:
            - "Create List A -> C + B -> D"
          filters:
            tags:
              only: /^(a|b)-.*/

      - npm_install_approve:
          type: approval

      - npm_install_no_cache:
          name: 01 NPM no cache install
          requires:
            - npm_install_approve
      - npm_install_no_cache:
          name: 02 NPM no cache install
          requires:
            - 01 NPM no cache install

      - npm_install_no_cache:
          name: 01 NPM no cache clean install
          command: ci
          requires:
            - npm_install_approve
      - npm_install_no_cache:
          name: 02 NPM no cache clean install
          command: ci
          requires:
            - 01 NPM no cache clean install

      - npm_install_cached_in_workspace:
          name: 01 NPM cached in workspace install
          requires:
            - npm_install_approve
      - npm_install_cached_in_workspace:
          name: 02 NPM cached in workspace install
          requires:
            - 01 NPM cached in workspace install

      - npm_install_cached_in_workspace:
          name: 01 NPM cached in workspace clean install
          command: ci
          requires:
            - npm_install_approve
      - npm_install_cached_in_workspace:
          name: 02 NPM cached in workspace clean install
          command: ci
          requires:
            - 01 NPM cached in workspace clean install

      - npm_install_cached_in_cache:
          name: 01 NPM cached in cache install
          requires:
            - npm_install_approve
      - npm_install_cached_in_cache:
          name: 02 NPM cached in cache install
          requires:
            - 01 NPM cached in cache install

      - npm_install_cached_in_cache:
          name: 01 NPM cached in cache clean install
          command: ci
          requires:
            - npm_install_approve
      - npm_install_cached_in_cache:
          name: 02 NPM cached in cache clean install
          command: ci
          requires:
            - 01 NPM cached in cache clean install
